# environment.yml
name: deco-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - h5py=3.15.0
  - networkx=3.5
  - tqdm=4.67.1
  - requests=2.32.4
  - urllib3=2.5.0
  - matplotlib=3.10.7
  - pip